language: go
os:
  - linux
  - osx
go:
  - 1.12.x
go_import_path: github.com/kataras/iris
# we disable test caching via GOCACHE=off
# env:
#  global:
#    - GOCACHE=off
install:
  - go get ./...
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
  # typescript examples
  - cd ./typescript/_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../../
  # make sure that the _benchmarks code is working
  - cd ./_benchmarks
  - go get ./...
  - go test -v -cover ./...